language: c
compiler: gcc
sudo: required
addons:
    apt:
        packages:
            - ubuntu-dev-tools
            - dput
            - debhelper
            - fakeroot
            - pkg-kde-tools

matrix:
    include:
        - os: linux
          env:
              - TARGET_DISTROS=xenial
              - TARGET_ENVIRONMENT=ubuntu-xenial
              - TARGET_CC=gcc
        - os: linux
          env:
              - TARGET_DISTROS=xenial
              - TARGET_ENVIRONMENT=ubuntu-xenial
              - TARGET_CC=clang
              - WITHOUT_PACKAGING=1
        - os: linux
          env:
              - TARGET_DISTROS=trusty
              - TARGET_ENVIRONMENT=ubuntu-trusty
              - TARGET_CC=gcc

script:
    - docker build --rm -t ${TARGET_ENVIRONMENT}-${TARGET_CC} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT}-${TARGET_CC} .

after_success:
    - ${TRAVIS_BUILD_DIR}/misc/ci-scripts/packaging.sh

deploy:
    provider: script
    skip_cleanup: true
    on:
        all_branches: true
        condition: -r ${TRAVIS_BUILD_DIR}/misc/ci-scripts/deploy-launchpad.sh
    script:
        - sh ${TRAVIS_BUILD_DIR}/misc/ci-scripts/deploy-launchpad.sh
